### ISSUE TITLE
iOS wallet transaction

### ISSUE THREAD

**Issue by speakfx** [CREDITSCOM/ewa#5]
**Issue 1**

When completing the transfer transaction of 0.3 CS from the wallet app, on the completion page it shows fee as 0.1 CS on the app. However, if we open monitor the actual fee was 0.0004287109375 CS. The balance is as per what monitor shows. Hence I think the fee displayed on the iOS as while performing the transaction (i.e. 0.1 CS fee) is not correct

![Image-1 (3)](https://user-images.githubusercontent.com/48795541/59548331-c9fcda80-8f5e-11e9-9d83-c65effbf27b7.jpg)

Other Observations

- Please include senders ID on the confirmation page at the end of the transaction in iOS
- On the iOS app, after completing the transaction and checking the monitor link to view transaction, I can see the receiver/sender address and there is a clipboard copy button. However that button is not working. It does not copy anything.

**Comment by botstorm** [comment]
This indicates the maximum commission you are willing to pay.
As a result, it will be much less specified.

**Comment by maianhkhoa** [comment]
Yeah it's kinda confusing at first. Hopefully dev will change it to Max Fee. Add a little question mark says "Maximum fee you are willing to pay"
